version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: matchpoint-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: matchpoint-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
      - SPRING_DATASOURCE_USERNAME=postgres.pcfwdibqnpvikdntgypw
      - SPRING_DATASOURCE_PASSWORD=Weekend@30303131
      - JWT_SECRET=dGhpcy1pcy1hLXNlY3VyZS1zaWduaW5nLWtleS1mb3ItbWF0Y2hwb2ludC1iYWRtaW50b24tbGVhZ3VlLXN5c3RlbS1iYWNrZW5kLXByb2plY3Q=
    depends_on:
      - db
    restart: always

volumes:
  pgdata:
